version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    env_file: 
      - .env
    networks: 
      - wordpress_site
    restart: always

  wordpress:
    image: wordpress:5.6.2-php7.3
    container_name: wordpress
    volumes: 
      - ./wordpress:/var/www/html
    env_file: 
      - .env
    environment: 
      WORDPRESS_DB_HOST: db
    ports:
      - 8080:80
    depends_on:
      - db
    networks: 
      - wordpress_site
    restart: always

networks: 
  wordpress_site: